#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
export const normalize=s=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(crtani film|cartoon|epizoda|episode|full)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
export function matchEntry(title,entries){const t=` ${normalize(title)} `;return entries.filter(e=>t.includes(` ${normalize(e.title)} `)).sort((a,b)=>b.title.length-a.title.length)[0]??null}
function jsonAfter(html,marker){const m=html.indexOf(marker),start=html.indexOf('{',m);let d=0,q=false,e=false;for(let i=start;i<html.length;i++){const c=html[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')q=false}else if(c==='"')q=true;else if(c==='{')d++;else if(c==='}'&&--d===0)return JSON.parse(html.slice(start,i+1))}throw Error('YouTube data not found')}
function walk(x,fn){if(!x||typeof x!=='object')return;fn(x);Object.values(x).forEach(v=>walk(v,fn))}
async function main(){const dry=process.argv.includes('--dry-run'),sources=JSON.parse(await fs.readFile('scripts/youtube-sources.json'));const index=JSON.parse(await fs.readFile('public/api/index.json'));const entries=index.cartoons.map(x=>({...x,path:path.join('public/api',x.file)}));for(const source of sources){const r=await fetch(source.url,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${r.status} ${source.url}`);const data=jsonAfter(await r.text(),'ytInitialData');const found=[];walk(data,n=>{const v=n.videoRenderer??n.gridVideoRenderer;if(v?.videoId){const title=v.title?.runs?.map(x=>x.text).join('')??v.title?.simpleText;if(title)found.push({id:v.videoId,title,url:`https://www.youtube.com/watch?v=${v.videoId}`,embedUrl:`https://www.youtube-nocookie.com/embed/${v.videoId}?autoplay=1&rel=0`,thumbnailUrl:`https://i.ytimg.com/vi/${v.videoId}/hqdefault.jpg`,durationText:v.lengthText?.simpleText??null,publishedText:v.publishedTimeText?.simpleText??null,source:{type:'youtube',name:source.name,url:source.url}})}});for(const video of found){const meta=matchEntry(video.title,entries);if(!meta)continue;const entry=JSON.parse(await fs.readFile(meta.path));entry.schemaVersion=2;entry.videos=[...new Map([...(entry.videos??[]),video].map(v=>[`${v.source.type}:${v.id}`,v])).values()];if(!dry)await fs.writeFile(meta.path,JSON.stringify(entry,null,2)+'\n');console.log(`${dry?'Would update':'Updated'} ${meta.path}`)}}}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error(e.message);process.exitCode=1});
